#!/bin/bash
# chkconfig: 3 21 91
#
# Virtual Clouddrive
#
# description: Start up the Virtual Clouddrive WebDAV daemon.
 
 
RETVAL=$?
#Chaneg to suit your needs
CLOUDDRIVE_HOME=/usr/local/clouddrive
#Ditto
CLOUDDRIVE_USER=clouddrive
 
case "$1" in
  start)
    if [ -f $CLOUDDRIVE_HOME/bin/start-cloudrive.sh ];
      then
      echo $"Starting Clouddrive"
      /bin/su - $CLOUDDRIVE_USER -c $CLOUDDRIVE_HOME/bin/start-cloudrive.sh > $CLOUDDRIVE_HOME/clouddrive.log 2>&1 &
    fi
  ;;
 
  stop)
    if [ -f $CLOUDDRIVE_HOME/bin/stop-cloudrive.sh ];
      then
      echo $"Stopping Clouddrive"
      /bin/su - $CLOUDDRIVE_USER -c $CLOUDDRIVE_HOME/bin/stop-clouddrive.sh
    fi
  ;;
 
  *)
    echo $"Usage: $0 {start|stop}"
    exit 1
  ;;
esac
 
exit $RETVAL